name: Build
on:
    workflow_dispatch:
jobs:
    build-lambda:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: 3.9
        - uses: aws-actions/setup-sam@v2
          with:
            use-installer: true
        - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - run: sam build -u

        - run: sam deploy
          env:
              AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
              AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
              AWS_REGION: us-east-1
